### ISSUE TITLE
Loader layer list

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#53]
Stacktrace to come

**Comment by sgrellet** [comment]
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 143, in on_validateButton_clicked
    self.validate()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 150, in validate
    self.layerList.setTitle('Layers')
AttributeError: 'ImportGmlasPanel' object has no attribute 'layerList'

when opening in GMLAS mode and pressing 'Load layer list' the attached file
[20180116_EF_PZ2.zip](https://github.com/BRGM/gml_application_schema_toolbox/files/1695299/20180116_EF_PZ2.zip)

**Comment by sgrellet** [comment]
on v1.2.0-rc2
either doing 'Load from file or URL' (using http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2) or 'Load a GMLAS database' (from previous toolbox generated .sqlite that worked in the GUI) I have

AttributeError: 'NoneType' object has no attribute 'endswith' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_panel.py", line 320, in on_loadFromFileButton_clicked
    self.gmlas_panel.do_load()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 320, in do_load
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 115, in import_in_qgis
    QgsProject.instance().addMapLayer(l)
AttributeError: 'NoneType' object has no attribute 'endswith'


Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.0-Girona Girona, 001c80b0c3

**Comment by mhugo** [comment]
Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/3a76a8a767021a126e09584e9df8fbc61ee84fd5

**Comment by sgrellet** [comment]
on GMLAS toolbox plugin : v1.2.0-rc4

LoadLayer list on this URI : http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2 

RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 154, in on_loadLayersButton_clicked
    self.validate()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 162, in validate
    data_source = self.gmlas_datasource()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 147, in gmlas_datasource
    open_options=openOptions)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\osgeo\gdal.py", line 2918, in OpenEx
    return _gdal.OpenEx(*args, **kwargs)
RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2

whereas it loads the layers ok using : http://ressource.brgm-rec.fr/data/EntiteHydroGeol/113AI01

Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw

**Comment by sgrellet** [comment]
load layer list was crashing because of #11 
but having solved the loadlayerlist issue I still cannot generate the SQLite db (all attributes in their default value) on this URI

AttributeError: 'NoneType' object has no attribute 'endswith' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard.py", line 147, in validatePage
    self._panel.do_load()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 328, in do_load
    import_in_qgis(dest, db_format, schema)
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 115, in import_in_qgis
    if field_xpath.endswith("@xlink:href"):
AttributeError: 'NoneType' object has no attribute 'endswith'

Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw

**Comment by mhugo** [comment]
The load layer list problem should be fixed with https://github.com/BRGM/gml_application_schema_toolbox/commit/efc05906ae947ccae27e7d11728dc676a8e8840a

I can't reproduce the other problem of "endsWith" with http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2 (tested both under linux and windows)

**Comment by sgrellet** [comment]
I confirm I still have the problement under v1.2.0-rc5
either using
http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2
or http://ressource.brgm-rec.fr/data/EntiteHydroGeol/121AU

I guess, as for the vsicurl_streaming, I need to try in command line (ogrinfo) and check the logs

**Comment by mhugo** [comment]
@sgrellet Hmmm could you retest by specifying a path for the sqlite file and send it to me ?

**Comment by sgrellet** [comment]
good guess. we have an error message but still the sqllite file is generated. attached
[20180413_EF_PZ.zip](https://github.com/BRGM/gml_application_schema_toolbox/files/1907802/20180413_EF_PZ.zip)

**Comment by mhugo** [comment]
Thanks. Could you try to open it back with the "Load a GMLAS database" feature of the plugin ? I am still struggling to reproduce ...

**Comment by mhugo** [comment]
Now I can reproduce under Windows.

**Comment by sgrellet** [comment]
fixed under GMLAS toolbox plugin : v1.2.0-rc6
Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw
tested using 
http://ressource.brgm-rec.fr/data/Piezometre/02713X0132/PZ-8.2
or http://ressource.brgm-rec.fr/data/EntiteHydroGeol/121AU
